### ISSUE TITLE
Temporarily Disabled Error

### ISSUE THREAD

**Issue by tshauck** [mcfunley/experiment-model#2]
From the site:

> Site temporarily disabled
> 
> This page has been temporarily disabled due to a misconfigured custom domain.
> 
> Are you the site owner? Follow the instructions for setting up a custom domain with GitHub pages to update your site's DNS records to point to the proper IP address.
> 
> You can find more information in our GitHub Pages legacy IP deprecation blog post. If you have any questions, please contact support.

**Comment by mcfunley** [comment]
Thanks--github made changes to the way pages work. I'll fix it as soon as I can.

**Comment by mcfunley** [comment]
I updated the dns records per [github's instructions](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/). 

I think that you were seeing what they were calling a "brownout," intended to prod me to fix the thing. The site seems to be currently working (with the old DNS records still in place). 

The changes will take a while to propagate. If I screwed it up somehow, you should always be able to see the site here: http://mcfunley.github.io/experiment-model/
